### ISSUE TITLE
Installation Consultation

### ISSUE THREAD

**Issue by domainbf** [obl-ong/panel#192]
This is a very good project. I came across obl.ong and I like it very much.
I have a lot of idle domain names, parking, or open subdomains are all very good choices.

Does obl have more installation instructions?

Or is there any other installation plan?

**Comment by youngchief-btw** [comment]
Hey! Steering committee member and systems administrator @ Obl.ong here.
Currently you just follow along in the "Building" section of the README. 
We're hoping to make a Dockerfile soon to help with self-hosting!
One important detail to note since you mention multiple domains: We don't currently have multi-domain support but that should be coming soon! 
Also if you ever need to reach us, our email is the best way to go for non-bugs which are best filed here if possible (team@obl.ong)!

**Comment by domainbf** [comment]
Okay, got it. Thank you.

**Comment by reesericci** [comment]
Just thought I would chime in here - I think the easiest way to install Obl.ong is on an Ubuntu Server virtual machine from the likes of Digital Ocean, or using a managed Rails hosting provider like Heroku. If you have any specific questions I'm also happy to answer them. Sorry about the lack of complete docs on this, it's really my bad on that one.

**Comment by domainbf** [comment]
> Just thought I would chime in here - I think the easiest way to install Obl.ong is on an Ubuntu Server virtual machine from the likes of Digital Ocean, or using a managed Rails hosting provider like Heroku. If you have any specific questions I'm also happy to answer them. Sorry about the lack of complete docs on this, it's really my bad on that one.
😅
Thank you very much for your guidance, but for me, I can't install it by myself. My skills are limited, and I only know a little bit about installing PHP-guided operations such as WordPress. I have built an management panel on my own server, and I can't understand the current installation method of obl at all. I look forward to his subsequent simple installation method.

**Comment by reesericci** [comment]
Basically, you'll need to find a guide for how to install a Ruby on Rails app, then follow the instructions in the README to configure it (You'll need a DNSimple API Key and a Postmark API key)

**Comment by domainbf** [comment]
OK, thanks,

I'll try to understand it first.
